# Generated by Django 3.2.6 on 2021-08-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=10)),
                ('enteredAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('expenseAmount', models.FloatField()),
                ('personName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.income')),
            ],
        ),
    ]
